### ISSUE TITLE
Can't read tags

### ISSUE THREAD

**Issue by TomTomTomnz** [Telerik-Verified-Plugins/NFC-DemoApp#1]
Hi,

Any chance you could help me out with the following problem I'm having with this demo app.

Once installed it wont read any tags.  If I click "NFC enabled?" it alerts "yes!"  If I click start listening it says "You can now scan a tag"  When I scan a tag, the phone beeps as though it has read a tag but nothing happens on the app.  I've tried putting an alert('Test'); in nfcHandler: function (nfcEvent) { however this alert never appears.

Any ideas how to solve this?  I can confirm that other nfc reader apps can successfully read these tags.

Thanks for any help it is most appreciated,

Tom

**Comment by EddyVerbruggen** [comment]
Which Android device and version is this exactly?

**Comment by TomTomTomnz** [comment]
Hi Eddy, thank you for the Reply.  Samsung A3 (SM-A300Y) Android Version 5.0.2

I've tried 2 tags.  One is an infochip tag iso 15693 if that helps?

**Comment by TomTomTomnz** [comment]
nxp icode slix

**Comment by TomTomTomnz** [comment]
Hi Eddy,

Any update on this?  Do you have a compiled version that I could test to ensure I'm not doing something wrong with building it?

**Comment by EddyVerbruggen** [comment]
Could be this Cordova version removed a deprecated method that is relied upon to send the result back to JavaScript. I've just pushed a change to the plugin's repo - can you please retest with version 0.6.6.1?

**Comment by TomTomTomnz** [comment]
Hi Thanks for your reply and sorry for my late reply.  I tried this and it still didn't work.  In addition I tried on an S6 and also tried with a credit card tag.  MiFare Classic 4k - emulated 6212 classic.  Do you have a compiled version of the app that you know works that I can test?

**Comment by EddyVerbruggen** [comment]
The only app I have is just loading this demo app into Telerik Platform and building it without any additional changes. BUT I don't currently have any NFC tags so I can't confirm it works.

[Here's the compiled APK for you to try](https://dl.dropboxusercontent.com/u/10061342/NFC.apk)

**Comment by TomTomTomnz** [comment]
Hi Eddy, thanks for your reply and for the compiled version.  Did you build this with 0.6.6.1?  It still will not read the tag, however when the phone reads a tag and beeps the program crashes with the message.  "Unfortunately NFC plugin demo has stopped".  This wasn't happening with the previous version of the plugin.  With the previous version the phone would beep and nothing would happen, so some progress!

**Comment by EddyVerbruggen** [comment]
Hi Tommonz, I just released 0.6.6.2 and added it to this demo app. Please try again!

**Comment by TomTomTomnz** [comment]
Hi Eddy,

Thanks for your reply.  I have tried .6.6.2 and unfortunately it still doesn't work (however doesn't crash).  Here is an excerpt from the log from .6.6.1

07-20 10:34:27.034: D/PersonaManager(25644): isNFCAllowed
07-20 10:34:27.034: W/System.err(25644): at com.chariotsolutions.nfc.plugin.NfcPlugin.sendJavascript(NfcPlugin.java:769)
07-20 10:34:27.034: W/System.err(25644): at com.chariotsolutions.nfc.plugin.NfcPlugin.fireTagEvent(NfcPlugin.java:664)
07-20 10:34:27.034: W/System.err(25644): at com.chariotsolutions.nfc.plugin.NfcPlugin.access$1000(NfcPlugin.java:34)
07-20 10:34:27.034: W/System.err(25644): at com.chariotsolutions.nfc.plugin.NfcPlugin$9.run(NfcPlugin.java:634)
07-20 10:34:27.044: E/AndroidRuntime(25644): Process: com.telerik.plugindemo.nfc, PID: 25644
07-20 10:34:27.044: E/AndroidRuntime(25644): at com.chariotsolutions.nfc.plugin.NfcPlugin.sendJavascript(NfcPlugin.java:769)
07-20 10:34:27.044: E/AndroidRuntime(25644): at com.chariotsolutions.nfc.plugin.NfcPlugin.fireTagEvent(NfcPlugin.java:664)
07-20 10:34:27.044: E/AndroidRuntime(25644): at com.chariotsolutions.nfc.plugin.NfcPlugin.access$1000(NfcPlugin.java:34)
07-20 10:34:27.044: E/AndroidRuntime(25644): at com.chariotsolutions.nfc.plugin.NfcPlugin$9.run(NfcPlugin.java:634)
07-20 10:34:27.044: V/ApplicationPolicy(1002): isApplicationStateBlocked userId 0 pkgname com.telerik.plugindemo.nfc
07-20 10:34:27.054: W/ActivityManager(1002):   Force finishing activity com.telerik.plugindemo.nfc/.TelerikCallbackActivity
07-20 10:34:27.054: V/ApplicationPolicy(1002): isApplicationStateBlocked userId 0 pkgname com.telerik.plugindemo.nfc
07-20 10:34:27.124: D/CrashAnrDetector(1002): processName: com.telerik.plugindemo.nfc
07-20 10:34:27.124: D/CrashAnrDetector(1002): broadcastEvent : com.telerik.plugindemo.nfc data_app_crash
07-20 10:34:27.144: D/NfcPlugin(25644): onPause Intent { act=android.nfc.action.TAG_DISCOVERED flg=0x34000000 cmp=com.telerik.plugindemo.nfc/.TelerikCallbackActivity (has extras) }
07-20 10:34:27.144: D/NfcPlugin(25644): stopNfc
07-20 10:34:31.944: I/ActivityManager(1002): Process com.telerik.plugindemo.nfc (pid 25644)(adj 15) has died(65,396)

**Comment by TomTomTomnz** [comment]
Hi Eddy,

Here is the debug for .6.1.2 it looks like you have resolved the previous issue and a tag is being read by this value is not getting passed back up to cordova?  Or the event handler isn't working?  Thoughts?

Cheers,

Tom

07-20 11:13:53.776: I/Timeline(1491): Timeline: Activity_launch_request id:com.telerik.plugindemo.nfc time:5427809
07-20 11:13:53.786: V/ApplicationPolicy(1002): isApplicationStateBlocked userId 0 pkgname com.telerik.plugindemo.nfc
07-20 11:13:53.786: W/ActivityManager(1002): NORMAL SET : srcAppInfo.processName = com.sec.android.app.launcher, destAppInfo.processName = com.telerik.plugindemo.nfc
07-20 11:13:53.796: V/ApplicationPolicy(1002): isApplicationStateBlocked userId 0 pkgname com.telerik.plugindemo.nfc
07-20 11:13:53.826: I/ActivityManager(1002): Start proc com.telerik.plugindemo.nfc for activity com.telerik.plugindemo.nfc/.TelerikCallbackActivity: pid=30886 uid=10310 gids={50310, 9997, 3003} abi=armeabi-v7a
07-20 11:13:54.426: E/Vold(256): Failed to find mounted volume for /storage/extSdCard/Android/data/com.telerik.plugindemo.nfc/cache/
07-20 11:13:54.426: W/ContextImpl(30886): Failed to ensure directory: /storage/extSdCard/Android/data/com.telerik.plugindemo.nfc/cache
07-20 11:13:54.476: D/NfcPlugin(30886): onResume Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.telerik.plugindemo.nfc/.TelerikCallbackActivity (has extras) }
07-20 11:13:54.476: D/PersonaManager(30886): isNFCAllowed
07-20 11:13:54.656: I/Timeline(1002): Timeline: Activity_windows_visible id: ActivityRecord{35f4341e u0 com.telerik.plugindemo.nfc/.TelerikCallbackActivity t9309} time:5428681
07-20 11:13:55.866: D/NfcPlugin(30886): Enabling plugin Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.telerik.plugindemo.nfc/.TelerikCallbackActivity (has extras) }
07-20 11:13:55.876: D/PersonaManager(30886): isNFCAllowed
07-20 11:13:55.876: D/NfcPlugin(30886): parseMessage Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.telerik.plugindemo.nfc/.TelerikCallbackActivity (has extras) }
07-20 11:13:55.876: I/chromium(30886): [INFO:CONSOLE(18)] "Initialized the NfcPlugin", source: file:///android_asset/www/plugins/com.chariotsolutions.nfc.plugin/www/phonegap-nfc.js (18)
07-20 11:14:04.896: D/PersonaManager(1446): isNFCAllowed
07-20 11:14:04.906: W/ActivityManager(1002): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=android.nfc.action.TAG_DISCOVERED flg=0x24000000 cmp=com.telerik.plugindemo.nfc/.TelerikCallbackActivity (has extras) }
07-20 11:14:04.906: D/NfcPlugin(30886): stopNfc
07-20 11:14:04.906: D/NfcPlugin(30886): onNewIntent Intent { act=android.nfc.action.TAG_DISCOVERED flg=0x34000000 cmp=com.telerik.plugindemo.nfc/.TelerikCallbackActivity (has extras) }
07-20 11:14:04.906: D/NfcPlugin(30886): parseMessage Intent { act=android.nfc.action.TAG_DISCOVERED flg=0x34000000 cmp=com.telerik.plugindemo.nfc/.TelerikCallbackActivity (has extras) }
07-20 11:14:04.906: D/NfcPlugin(30886): action android.nfc.action.TAG_DISCOVERED
07-20 11:14:04.916: V/NfcPlugin(30886): e.tag = {"id":[111,66,43,82,0,3,4,-32],"techTypes":["android.nfc.tech.NfcV","android.nfc.tech.NdefFormatable"]};
07-20 11:14:04.916: D/PersonaManager(30886): isNFCAllowed

**Comment by AntonDobrev** [comment]
This should be fixed by using the latest plugin version and just the callback _addTagDiscoveredListener_

**Comment by EddyVerbruggen** [comment]
👍
